# Navbar Menus
[[nav]]
name = "editorial"
url = "editorial/"
weight = 1

  [[nav]]
  parent = "editorial"
  name = "Academia Abierta"
  url = "editorial/academia-abierta/"
  weight = 1

  [[nav]]
  parent = "editorial"
  name = "Cabecera editorial"
  url = "editorial/cabecera/"
  weight = 2

  [[nav]]
  parent = "editorial"
  name = "Objetivos editoriales"
  url = "editorial/objetivos-editoriales/"
  weight = 3

  [[nav]]
  parent = "editorial"
  name = "Declaración de principios"
  url = "editorial/declaracion-de-principios"
  weight = 4

[[nav]]
name = "propuestas"
url = "propuestas/"
weight = 2

  [[nav]]
  parent = "propuestas"
  name = "Nuevas monografías"
  url = "propuestas/nuevas-monografias"
  weight = 1

  [[nav]]
  parent = "propuestas"
  name = "Políticas editoriales"
  url = "/propuestas/politicas-editoriales"
  weight = 2

[[nav]]
name = "blog"
url = "blog/"
weight = 3

[[nav]]
name = "contacto"
url = "contacto/"
weight = 6

[[nav]]
name = "buscar"
url = "buscar/"
weight = 7

# Footer acciones Menu
[[acciones]]
name = "graphicdesign"
url = "acciones/"
weight = 1
[[acciones]]
name = "webdesign"
url = "acciones/"
weight = 2
[[acciones]]
name = "webdevelopment"
url = "acciones/"
weight = 3

# Footer Quick links Menu
[[quicklink]]
name = "partners"
url = "ofilibre/"
weight = 1
[[quicklink]]
name = "ofilibre"
url = "ofilibre/"
weight = 2
[[quicklink]]
name = "faqs"
url = "ofilibre/"
weight = 3
[[quicklink]]
name = "badges"
url = "ofilibre/"
weight = 4
