backend:
  name: turbo-github
  turbo_site_id: f5c8ad16-8cbe-49f9-b2aa-f4f4abd765ef
locale: es
media_folder: static
public_folder: /
collections:
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    media_folder: '/../../../static/blog/{{slug}}'
    public_folder: '/blog/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Categorías', name: 'categories', widget: 'hidden', default: ["Universidad"]}
      - { label: 'Etiquetas', name: 'tags', widget: 'list'}
      - { label: 'Logo', name: 'image', widget: 'image', default: '/logos/logo-ofilibre-2025.jpg'}
      - { label: 'Cuerpo', name: 'body', widget: 'richtext' }

  - label: 'Quiénes somos'
    name: 'editorial'
    files:
      - label: 'Editorial Academia Abierta'
        name: 'editorial'
        file: 'content/editorial/academia-abierta.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
      - label: 'Cabecera'
        name: 'cabecera'
        file: 'content/editorial/cabecera.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
      - label: 'Objetivos editoriales'
        name: 'objetivos-editoriales'
        file: 'content/editorial/objetivos-editoriales.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
      - label: 'Declaración de principios'
        name: 'declaracion-de-principios'
        file: 'content/editorial/declaracion-de-principios.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }

  - label: 'Propuestas'
    name: 'propuestas'
    files:
      - label: 'Nuevas monografías'
        name: 'nuevas-monografias'
        file: 'content/propuestas/nuevas-monografias.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
      - label: 'Políticas editoriales'
        name: 'politicas-editoriales'
        file: 'content/propuestas/politicas-editoriales.md'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'richtext' }